name: Automated Merge Workflow

on:
  push:
    branches:
      - source # Adjust to the branch you want to trigger the merge from
  workflow_run:
    workflows: ["Run Merge Workflow"] # This triggers the merge workflow

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: PR
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.TOKEN }}
          source_branch: source
          target_branch: NewSource
          title: My pull request
          body: "**Automated pull request**"
          reviewer: bxsankar
          assignee: mxsunda1
          label: enhancement
          milestone: My milestone
          draft: true
          old_string: "<!-- Add your description here -->"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"
          allow_no_diff: false
     
     
